test:
  unet_path: /work/scratch/mcrespo/output/test_12_26/12-26_11h44m10s/selora_outputs/loras/trained_model/final_Unet/diffusion_pytorch_model.safetensors
  txt_encoder_path: /work/scratch/mcrespo/output/test_12_26/12-26_11h44m10s/selora_outputs/loras/trained_model/final_Text/model.safetensors
  imgs_folder:  /work/scratch/mcrespo/output/test_12_26/test_imgs

output:
  path: /work/scratch/mcrespo/output/test_12_26_alldataset
  folder_name: /selora_outputs
  folder_lora_name: /loras

dataset:
  main_path: /home/mcrespo/migros_deepL
  # dataset_name: /BraTS2021_final
  dataset_name: /BraTS2021_final
  sequence_type: /Flair_final
  report_name: /metadata.csv
  

default_random_seed: 42
batch_size: 8
lr: 1.e-4

model:
  model_id: runwayml/stable-diffusion-v1-5
  unet_modules: {"to_q", "to_k", "to_v"}
  txt_encoder_modules: {"q_proj", "k_proj", "v_proj"}
  rank: 4
  expandable: False
