test:
  unet_path: /work/scratch/mcrespo/output/test_22_12/12-22_17h22m22s/selora_outputs/loras/trained_model/final_Unet/diffusion_pytorch_model.safetensors
  txt_encoder_path: /work/scratch/mcrespo/output/test_22_12/12-22_17h22m22s/selora_outputs/loras/trained_model/final_Text/model.safetensors
  imgs_folder:  /work/scratch/mcrespo/output/test_22_12/test_imgs

output:
  path: /work/scratch/mcrespo/output/test_22_12
  folder_name: /selora_outputs
  folder_lora_name: /loras

dataset:
  main_path: /home/mcrespo/migros_deepL
  # dataset_name: /BraTS2021_train
  dataset_name: /test_img
  sequence_type: /Flair
  report_name: /metadata.csv
  

default_random_seed: 42
batch_size: 2
lr: 1.e-4

model:
  model_id: runwayml/stable-diffusion-v1-5
  unet_modules: to_v
  txt_encoder_modules: v_proj
  rank: 4
  expandable: False
